---

- name: Install python3, git
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "{{ packages }}"
  vars:
    packages:
    - python3
    - git

- name: Create auto user
  register: createuser
  user:
    name: auto
    system: yes
    generate_ssh_key: yes

- name: Create site directory
  file:
    state: directory
    dest: /var/cache/gw-statuspage/site
    owner: auto
    recurse: yes

- name: Clone site
  become: true
  become_user: auto
  git:
    repo: "{{ git_addr }}/site.git"
    dest: /var/cache/gw-statuspage/site
    accept_hostkey: true
  register: site

- name: Add cron job for git pull of site
  cron:
    name: "gw-statuspage site git pull"
    user: "auto"
    minute: "4,44"
    hour: "5"
    job: "cd /var/cache/gw-statuspage/site; git pull >/dev/null 2>&1"

- name: Add aiyions repository to apt
  deb822_repository:
    name: grafana
    types: deb
    uris: http://aiyionpri.me/repo/
    suites: ./
    architectures: amd64
    signed_by: "https://aiyionpri.me/repo/aiyionprime.gpg"
    # id: 961988DB578E33B3E2812463F3CD90145E0C0947
  register: repo

- name: Update apt cache
  apt:
    update_cache: yes
  when: repo.changed or gpg.changed

- name: Install or update gw-statuspage
  apt:
    name: gw-statuspage
    state: latest

- name: Enable systemd service
  systemd:
    name: gw-statuspage
    enabled: yes

- name: Start systemd service
  systemd:
    name: gw-statuspage
    state: started
