---

- name: Install iptables
  apt:
    update_cache: yes
    name: "iptables"

- name: "Install iptables system service file"
  notify: "systemd daemon-reload"
  template:
    src: "iptables.service.j2"
    dest: "/etc/systemd/system/iptables-forward.service"
    mode: "0644"
    owner: "root"
    group: "root"

- name: Start and enable iptables-forward service
  systemd:
    name: iptables-forward
    state: started
    enabled: yes
    daemon_reload: yes
