---
- name: Add influx repository to apt
  deb822_repository:
    name: influx
    types: deb
    uris: https://repos.influxdata.com/debian
    suites: "{{ ansible_distribution_release }}"
    components: stable
    architectures: amd64
    signed_by: "https://repos.influxdata.com/influxdb.key"
  register: influxrepositoryadded

- name: Update apt chache to get influxdb packages
  apt: update_cache=yes
  when: influxrepositoryadded is changed

- name: Install influxdb2 from repo
  register: influxinstall
  apt:
    name: influxdb2
    state: latest

- name: Generate config file
  register: influx2_configfile
  template:
    src: influx2.config.toml.j2
    dest: /etc/influxdb/config.toml

- name: Ensure engine directory exists and has correct ownership
  file:
    state: directory
    path: "{{ influx2_engine_path }}"
    owner: "influxdb"
    group: "influxdb"
    recurse: yes

# - name: Generate firewall config stanza (ferm)
#   register: ferm_changed
#   template:
#     src: ferm.conf.j2
#     dest: /etc/ferm/conf.d/50-influxdb.conf
#   notify: reload ferm

- name: Reload influxdb2 service
  systemd:
    name: influxdb
    state: restarted
    daemon_reload: yes
    enabled: yes
  when: influx2_configfile is changed

- name: setup influxdb if not done yet
  command: influx setup -u freifunk -p freifunk -o freifunk -b freifunk -r 0 -f -t {{ influx2_token }}
  when: influxinstall is changed
