{
 "title": "Globals",
 "tags": [
  "nodes",
  "network",
  "public"
 ],
 "time": { "from": "now-30d", "to": "now-1m" },
 "panels": [
  {
   "title": "Globals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col FastD",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "global",
     "query": "SELECT mean(\"clients.wifi24\") AS \"Clients 2.4 Ghz\", mean(\"clients.total\") AS \"Clients Total\", mean(\"nodes\") AS \"Nodes\" FROM \"global\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "clients.wifi24" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Clients 2.4 Ghz" ], "type": "alias" }
      ],
      [
       { "params": [ "clients.total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Clients Total" ], "type": "alias" }
      ],
      [
       { "params": [ "nodes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Nodes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=", "value": "ffac" }
     ]
    },
    {
     "alias": "$col WG",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "global",
     "query": "SELECT mean(\"clients.wifi24\") AS \"Clients 2.4 Ghz\", mean(\"clients.total\") AS \"Clients Total\", mean(\"nodes\") AS \"Nodes\" FROM \"global\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "clients.wifi24" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Clients 2.4 Ghz" ], "type": "alias" }
      ],
      [
       { "params": [ "clients.total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Clients Total" ], "type": "alias" }
      ],
      [
       { "params": [ "nodes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Nodes" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "site", "operator": "=", "value": "ffac-wg" }
     ]
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_value",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"count\") FROM \"firmware\" WHERE $timeFilter GROUP BY time($interval), \"value\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Autoupdater",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_value",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "value" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "autoupdater",
     "query": "SELECT mean(\"count\") FROM \"firmware\" WHERE $timeFilter GROUP BY time($interval), \"value\" fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Model",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_value",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"count\") FROM \"model\" WHERE $timeFilter GROUP BY time($interval), \"value\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Clients",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "global",
     "query": "SELECT last(\"clients.total\") - last(\"clients.wifi\") as \"other\" , last(\"clients.wifi24\") as \"2.4 Ghz\",  last(\"clients.wifi5\") as \"5 Ghz\", last(\"clients.wifi\") -last(\"clients.wifi24\")-last(\"clients.wifi5\") as \"other-wifi\"  FROM \"global\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "clients.wifi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ],
      [
       { "params": [ "clients.wifi24" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "clients.wifi5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_value",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "value" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "firmware",
     "query": "SELECT mean(\"count\") FROM \"firmware\" WHERE $timeFilter GROUP BY time($interval), \"value\" fill(none)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Model",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_value",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "value" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "model",
     "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Knoten-Laufzeit in Tagen",
   "type": "histogram",
   "description": "Das Histogramm zeigt die Verteilung der Laufzeit aller Knoten in Tagen (bis max. 14 Tage).",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "laufzeit",
     "groupBy": [
      { "params": [ "nodeid" ], "type": "tag" }
     ],
     "measurement": "node",
     "query": "SELECT last(\"time.up\")/ FROM \"node\" WHERE (\"time.up\" < 1209600) AND $timeFilter GROUP BY \"nodeid\"\nSELECT last(\"time.up\") / 86400.0 FROM \"node\" WHERE time.up <= 1209600 AND $timeFilter GROUP BY \"nodeid\"",
     "select": [
      [
       { "params": [ "time.up" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 86400" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "time.up", "operator": "<", "value": "1209600" }
     ]
    }
   ]
  },
  {
   "title": "Traffic pro domain",
   "type": "timeseries",
   "description": "Regio ist FastD - ffac ist WG",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "alias": "$col $tag_site",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "site" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "node",
     "select": [
      [
       { "params": [ "traffic.forward.bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "forward" ], "type": "alias" }
      ],
      [
       { "params": [ "traffic.rx.bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "rx" ], "type": "alias" }
      ],
      [
       { "params": [ "traffic.tx.bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "tx" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}