---

- name: Install dependencies
  apt:
    update_cache: yes
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - gpg
    # required for image renderer plugin
    - libasound2
    - libgbm-dev
    - libnss3

- name: Add grafana repository to apt
  deb822_repository:
    name: grafana
    types: deb
    uris: https://packages.grafana.com/oss/deb
    suites: stable
    components: main
    architectures: amd64
    signed_by: "https://packages.grafana.com/gpg.key"
  register: keyadded

- name: Install grafana
  apt:
    update_cache: yes
    name: grafana
  when: keyadded is changed

- name: Generate grafana config
  notify: Restart grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini

- name: Permissions on data directory
  file:
    state: directory
    path: "{{ grafana_datadir }}"
    owner: "grafana"
    group: "grafana"
    recurse: yes

- name: Change DATA_DIR in /etc/default/grafana-server
  lineinfile:
    dest: /etc/default/grafana-server
    regexp: '^(DATA_DIR=).*'
    line: 'DATA_DIR={{ grafana_datadir }}'
    state: present

- name: Install provisioning files
  copy:
    src: "grafana/dashboard-definitions"
    dest: "{{ grafana_datadir }}/provisioning"
    owner: "grafana"
    group: "grafana"

- name: ensures dashboards dir exists
  file: 
    path: "{{ grafana_datadir }}/provisioning/dashboards"
    state: directory

- name: ensures datasources dir exists
  file: 
    path: "{{ grafana_datadir }}/provisioning/datasources"
    state: directory

- name: Install dashboards files
  template:
    src: "dashboards/dashboards.yaml"
    dest: "{{ grafana_datadir }}/provisioning/dashboards/dashboards.yaml"
    owner: "grafana"
    group: "grafana"

- name: Install datasources files
  template:
    src: "datasources/datasources.yaml"
    dest: "{{ grafana_datadir }}/provisioning/datasources/datasources.yaml"
    owner: "grafana"
    group: "grafana"

- name: Enable grafana
  service:
    name: grafana-server
    enabled: yes
    state: started

- name: Install Image renderer plugin
  raw:
    grafana-cli plugins install grafana-image-renderer