---
servername: bb-b

public_ffrl_ffac_prefix: 185.66.193.40/29
# cloud-init config
networkd_interfaces:
  - name: eth1
    addresses:
      - 100.64.17.142/24
    routing_policies:
      - from: "{{ public_ffrl_ffac_prefix }}"
        table: 42
  - name: eth0
    addresses:
      - 5.145.135.142/27
      - 2a00:fe0:43::bb:2/64
    gateway4: 5.145.135.129
    gateway6: 2a00:fe0:43::1
    dns_server:
      - 9.9.9.9
      - '2a03:2260:3006::53'
    additional_config: |      
      Tunnel=bb-ber-a
      Tunnel=bb-ber-b
      Tunnel=bb-dus-a
      Tunnel=bb-dus-b
      Tunnel=bb-fra-a
      Tunnel=bb-fra-b
    static_routes:
      - destination: 2a03:2260:3006:100::/56
        gateway: 2a00:fe0:43::201
      - destination: 2a03:2260:3006:100::/56
        gateway: 2a00:fe0:43::201
        table: 42
      - destination: 2a03:2260:3006:200::/56
        gateway: 2a00:fe0:43::202
      - destination: 2a03:2260:3006:200::/56
        gateway: 2a00:fe0:43::202
        table: 42
    routing_policies:
      - from: 2a03:2260:3006:100::/56
        table: 42
      - from: 2a03:2260:3006:200::/56
        table: 42

gretunnel_configures:
  - netdev: bb-ber-a
    mtu_bytes: 1400
    local_address: 5.145.135.142
    remote_address: 185.66.195.0
    independent: yes
    ttl: 64
    networks:
      - address: 100.64.5.231/31
      - address: 2a03:2260:0:2f4::2/64
      - address: fe80::591:878d/64
        scope: local
  - netdev: bb-dus-a
    mtu_bytes: 1400
    local_address: 5.145.135.142
    remote_address: 185.66.193.0
    independent: yes
    ttl: 64
    networks:
      - address: 100.64.5.235/31
      - address: 2a03:2260:0:2f6::2/64
      - address: fe80::591:878d/64
        scope: local
  - netdev: bb-fra-a
    mtu_bytes: 1400
    local_address: 5.145.135.142
    remote_address: 185.66.194.0
    independent: yes
    ttl: 64
    networks:
      - address: 100.64.5.233/31
      - address: 2a03:2260:0:2f5::2/64
      - address: fe80::591:878d/64
        scope: local