---
servername: bgp-test

public_ffrl_ipv4: "185.66.193.46/32"
public_ffrl_ipv6: "2a03:2260:3006:a157::/56"
# cloud-init config
networkd_interfaces:
  - name: lo
    addresses:
      - "{{ public_ffrl_ipv4 }}"
      - "{{ public_ffrl_ipv6 }}"
    routing_policies:
      - from: "{{ public_ffrl_ipv6 }}"
        table: 42
      - from: "{{ public_ffrl_ipv4 }}"
        table: 42
  - name: eth0
    addresses:
      - 2a00:fe0:43::157/64
    gateway6: 2a00:fe0:43::1
    dns_server:
      - 9.9.9.9
      - '2a03:2260:3006::53'
  - name: eth1
    addresses:
      - 100.64.17.157/24

bird:
  router_id: 100.64.17.157
  kernel:
    - is_ipv6: no
      ip_table: 42
      exports:
        - "filter filter_kernel_v4"
    - is_ipv6: yes
      ip_table: 42
      # bird_table: auxtable
      exports:
        - "filter filter_kernel_v6"
  ospf:
    - version: v2
      name: IGP
      is_ipv6: no
      imports:
        - "all"
      exports:
        - "filter reject_internal_prefixes_v4"
        - "filter accept_public_prefix_v4"
      area:
        - id: 0
          interfaces:
            - name: lo
              stub: yes
            - name: eth1
              cost: 10
              hello: 5
              retransmit: 2
              wait: 10
              dead: 20
              check: link
              authentication: "none"
    - version: v3
      name: IGP6
      is_ipv6: yes
      imports:
        - "all"
      exports:
        - "filter reject_internal_prefixes_v6"
        - "filter accept_public_prefix_v6"
      area:
        - id: 0
          interfaces:
            - name: lo
              stub: yes
            - name: eth1
              cost: 10
              hello: 5
              retransmit: 2
              wait: 10
              dead: 20
              check: link
              authentication: "none"
  filter:
    - name: reject_internal_prefixes_v4
      default_accept: yes
      rules:
        - "if net ~ [100.64.17.0/24+, 5.145.135.128/27+] then reject;"
    - name: accept_public_prefix_v4
      default_accept: no
      rules:
        - "if net ~ [185.193.64.40/29+] then accept;"
    - name: reject_internal_prefixes_v6
      default_accept: yes
      rules:
        - "if net ~ [2a00:fe0:43::/48+] then reject;"
    - name: accept_public_prefix_v6
      default_accept: no
      rules:
        - "if net ~ [2a03:2260:3006::/48+] then accept;"
    - name: filter_kernel_v4
      default_accept: yes
      rules:
        - "if net ~ [100.64.17.0/24+, 5.145.135.128/27+, 10.0.0.0/8+] then reject;"
        - "krt_prefsrc={{ public_ffrl_ipv4.split('/') | first }};"
    - name: filter_kernel_v6
      default_accept: yes
      rules:
        - "if net ~ [2a00:fe0:43::/48+] then reject;"
        - "krt_prefsrc={{ public_ffrl_ipv6.split('/') | first }};"